"""Katalog jalur karier yang digunakan form, ranking, dan tampilan ArahKita."""

CAREER_CATALOG = {
    "Data Analyst": {
        "label": "Data Analyst",
        "description": "Mengubah data menjadi insight yang membantu keputusan.",
        "icon": "📊",
        "skills": ["Excel", "SQL", "Statistics", "Data Visualization"],
        "related": ["Public Health Analyst", "Health Product / Business Analyst", "Data Scientist"],
        "activities": ["Mengolah data dan mencari pola"],
        "opportunity_goals": ["Data Analyst"],
        "action_group": "data",
    },
    "Data Scientist": {
        "label": "Data Scientist",
        "description": "Membangun analisis dan model prediksi berbasis data.",
        "icon": "🧠",
        "skills": ["Python", "SQL", "Statistics", "Machine Learning"],
        "related": ["AI / Machine Learning Engineer", "Bioinformatics Analyst", "Data Analyst"],
        "activities": ["Membuat model prediksi atau otomasi"],
        "opportunity_goals": ["Data Scientist"],
        "action_group": "data_science",
    },
    "Bioinformatics Analyst": {
        "label": "Bioinformatics Analyst",
        "description": "Mengolah data biologis dan genomik dengan pendekatan komputasi.",
        "icon": "🧬",
        "skills": ["Python", "R", "Statistics", "Bioinformatics"],
        "related": ["Data Scientist", "Researcher", "Public Health Analyst"],
        "activities": ["Menganalisis data biologis atau genomik", "Mengolah data dan mencari pola"],
        "opportunity_goals": ["Data Scientist", "Researcher"],
        "action_group": "data_science",
    },
    "Software/IT": {
        "label": "Software Developer / IT",
        "description": "Membangun sistem digital dan solusi teknologi yang dapat digunakan.",
        "icon": "💻",
        "skills": ["Python", "SQL", "Git", "API Development"],
        "related": ["AI / Machine Learning Engineer", "Health Product / Business Analyst", "Data Scientist"],
        "activities": ["Membangun aplikasi atau sistem digital"],
        "opportunity_goals": ["Software/IT"],
        "action_group": "technology",
    },
    "AI / Machine Learning Engineer": {
        "label": "AI / Machine Learning Engineer",
        "description": "Mengubah model AI menjadi fitur atau sistem yang berjalan.",
        "icon": "⚙️",
        "skills": ["Python", "SQL", "Machine Learning", "API Development"],
        "related": ["Data Scientist", "Software/IT", "Bioinformatics Analyst"],
        "activities": ["Membuat model prediksi atau otomasi", "Membangun aplikasi atau sistem digital"],
        "opportunity_goals": ["Data Scientist", "Software/IT"],
        "action_group": "technology",
    },
    "Researcher": {
        "label": "Biomedical Researcher",
        "description": "Menjawab masalah kesehatan melalui eksperimen dan bukti ilmiah.",
        "icon": "🔬",
        "skills": ["Research Methodology", "Laboratory Techniques", "Statistics", "Scientific Writing"],
        "related": ["Laboratory Analyst", "Clinical Research Associate", "Bioinformatics Analyst"],
        "activities": ["Melakukan eksperimen di laboratorium"],
        "opportunity_goals": ["Researcher"],
        "action_group": "research",
    },
    "Clinical Research Associate": {
        "label": "Clinical Research Associate",
        "description": "Menjaga pelaksanaan dan data studi klinis tetap berkualitas.",
        "icon": "🩺",
        "skills": ["Research Methodology", "Clinical Data Management", "Regulatory Documentation", "Scientific Writing"],
        "related": ["Researcher", "Quality Assurance & Regulatory Affairs", "Public Health Analyst"],
        "activities": ["Mengelola riset klinis dan data pasien"],
        "opportunity_goals": ["Researcher", "Data Analyst"],
        "action_group": "research",
    },
    "Laboratory Analyst": {
        "label": "Laboratory Analyst",
        "description": "Melakukan pengujian laboratorium dan mendokumentasikan hasilnya.",
        "icon": "🧪",
        "skills": ["Laboratory Techniques", "Research Methodology", "Quality Management", "Excel"],
        "related": ["Researcher", "Quality Assurance & Regulatory Affairs", "Clinical Research Associate"],
        "activities": ["Melakukan eksperimen di laboratorium"],
        "opportunity_goals": ["Researcher"],
        "action_group": "research",
    },
    "Quality Assurance & Regulatory Affairs": {
        "label": "Quality Assurance / Regulatory Affairs",
        "description": "Memastikan produk dan proses memenuhi standar serta regulasi.",
        "icon": "✅",
        "skills": ["Quality Management", "Regulatory Documentation", "Scientific Writing", "Excel"],
        "related": ["Laboratory Analyst", "Clinical Research Associate", "Health Product / Business Analyst"],
        "activities": ["Memastikan mutu, keamanan, dan kepatuhan regulasi"],
        "opportunity_goals": ["Researcher"],
        "action_group": "quality",
    },
    "Public Health Analyst": {
        "label": "Public Health Analyst / Epidemiology",
        "description": "Membaca pola kesehatan populasi untuk mendukung intervensi.",
        "icon": "🌍",
        "skills": ["Statistics", "Excel", "Data Visualization", "Research Methodology"],
        "related": ["Data Analyst", "Clinical Research Associate", "Bioinformatics Analyst"],
        "activities": ["Mengolah data dan mencari pola", "Mengelola riset klinis dan data pasien"],
        "opportunity_goals": ["Data Analyst", "Researcher"],
        "action_group": "data",
    },
    "Health Product / Business Analyst": {
        "label": "Health Product / Business Analyst",
        "description": "Menghubungkan kebutuhan pengguna, data, dan solusi kesehatan.",
        "icon": "🧭",
        "skills": ["Excel", "Data Visualization", "Product Management", "Scientific Writing"],
        "related": ["Data Analyst", "Software/IT", "Quality Assurance & Regulatory Affairs"],
        "activities": ["Merancang produk atau layanan kesehatan"],
        "opportunity_goals": ["Data Analyst", "Software/IT"],
        "action_group": "product",
    },
    "Medical Writer / Science Communicator": {
        "label": "Medical Writer / Science Communicator",
        "description": "Menerjemahkan informasi medis menjadi konten yang akurat dan jelas.",
        "icon": "✍️",
        "skills": ["Scientific Writing", "Literature Review", "Research Methodology", "Data Visualization"],
        "related": ["Researcher", "Public Health Analyst", "Health Product / Business Analyst"],
        "activities": ["Menulis dan menjelaskan informasi sains"],
        "opportunity_goals": ["Researcher"],
        "action_group": "communication",
    },
}

ACTIVITY_TO_PRIMARY = {
    "Mengolah data dan mencari pola": "Data Analyst",
    "Membuat model prediksi atau otomasi": "Data Scientist",
    "Menganalisis data biologis atau genomik": "Bioinformatics Analyst",
    "Membangun aplikasi atau sistem digital": "Software/IT",
    "Melakukan eksperimen di laboratorium": "Researcher",
    "Mengelola riset klinis dan data pasien": "Clinical Research Associate",
    "Memastikan mutu, keamanan, dan kepatuhan regulasi": "Quality Assurance & Regulatory Affairs",
    "Merancang produk atau layanan kesehatan": "Health Product / Business Analyst",
    "Menulis dan menjelaskan informasi sains": "Medical Writer / Science Communicator",
}

GOALS = [*CAREER_CATALOG, "Undecided"]

SKILLS = [
    "Excel",
    "Python",
    "SQL",
    "R",
    "Statistics",
    "Data Visualization",
    "Machine Learning",
    "Bioinformatics",
    "Laboratory Techniques",
    "Research Methodology",
    "Clinical Data Management",
    "Quality Management",
    "Regulatory Documentation",
    "Scientific Writing",
    "Literature Review",
    "Product Management",
    "Git",
    "API Development",
]
